mysql-coworking:
    image: mysql:5.7.18
    volumes:
    - ./mysql/my-custom.cnf:/etc/mysql/conf.d/custom.cnf
    - ./mysql/script.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: coworking
        MYSQL_USER: springuser
        MYSQL_PASSWORD: springpassword
    ports:
    - 3306:3306
pma:
    image: phpmyadmin/phpmyadmin
    links:
    - mysql-coworking
    ports:
        - 81:80
    environment:
        PMA_HOST: mysql-coworking
